export const locationOptions = {
  Portugal: {
    Aveiro: ["Aveiro", "Agueda", "Espinho", "Santa Maria da Feira"],
    Beja: ["Beja", "Moura", "Serpa"],
    Braga: ["Braga", "Barcelos", "Guimaraes", "Vila Nova de Famalicao"],
    Braganca: ["Braganca", "Mirandela", "Macedo de Cavaleiros"],
    "Castelo Branco": ["Castelo Branco", "Covilha", "Fundao"],
    Coimbra: ["Coimbra", "Figueira da Foz", "Cantanhede", "Pombal"],
    Evora: ["Evora", "Estremoz", "Montemor-o-Novo"],
    Faro: ["Faro", "Albufeira", "Loule", "Portimao"],
    Guarda: ["Guarda", "Seia", "Gouveia"],
    Leiria: ["Leiria", "Pombal", "Marinha Grande", "Caldas da Rainha", "Peniche"],
    Lisboa: ["Lisboa", "Amadora", "Cascais", "Loures", "Odivelas", "Sintra"],
    Portalegre: ["Portalegre", "Elvas", "Ponte de Sor"],
    Porto: ["Porto", "Gondomar", "Maia", "Matosinhos", "Vila Nova de Gaia"],
    Santarem: ["Santarem", "Tomar", "Torres Novas", "Entroncamento"],
    Setubal: ["Setubal", "Almada", "Barreiro", "Sesimbra"],
    "Viana do Castelo": ["Viana do Castelo", "Ponte de Lima", "Valenca"],
    "Vila Real": ["Vila Real", "Chaves", "Peso da Regua"],
    Viseu: ["Viseu", "Lamego", "Tondela"],
    Acores: ["Ponta Delgada", "Angra do Heroismo", "Horta"],
    Madeira: ["Funchal", "Camara de Lobos", "Machico"],
  },
};
